version: '3.8'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: 'GRIN'
      MYSQL_USER: 'grinUser'
      MYSQL_PASSWORD: 'grinAdmin'
      MYSQL_ROOT_PASSWORD: 'admin'
    volumes:
      - db_data:/var/lib/mysql
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql

  backend:
    image: backend:latest
    ports:
      - 8081:8081
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=grinUser
      - MYSQL_PASSWORD=grinAdmin
      - MYSQL_DB=GRIN
    depends_on:
      - db
    build:
      context: ./Backend
      dockerfile: Dockerfile

  frontend:
    image: frontend:latest
    ports:
      - 5173:5173
    depends_on:
      - backend
    build:
      context: ./Frontend
      dockerfile: Dockerfile


volumes:
  db_data:
    driver: local