version: '3.8'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: 'GRIN'
      MYSQL_ROOT_PASSWORD: 'admin'
    volumes:
      - db_data:/var/lib/mysql
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    networks:
      - default

  backend:
    image: backend:latest
    ports:
      - 8081:8081
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=admin
      - MYSQL_DB=GRIN
    depends_on:
      - db
    build:
      context: ./Backend
      dockerfile: Dockerfile
    networks:
      - default


  frontend:
    image: frontend:latest
    ports:
      - 5173:5173
    depends_on:
      - backend
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=http://backend:8081
    networks:
      - default

volumes:
  db_data:
    driver: local

networks:
  default:
    driver: bridge

